package com.cosmo.web.sample;

import com.cosmo.orm.annotations.CormObjectField;
import com.cosmo.orm.annotations.CormObjectField.FieldSortType;
import com.cosmo.orm.annotations.CormFieldSetter;
import com.cosmo.orm.annotations.CormObject;
import com.cosmo.ui.controls.FormFieldInteger;
import com.cosmo.ui.controls.FormFieldText;

@CormObject(formName = "frmWeather", dbTable = "weather", title = "Registre de temperatures", description = "Introdueixi les dades per registrar les dades climatològiques d'una ciutat.")
public class Weather
{
   private Integer id;
   private String  cityName;
   private Integer tempMin;
   private Integer tempMax;
   private Integer precipitation;

   // ==============================================
   // Constructors
   // ==============================================

   /**
    * Constructor de la clase.
    */
   public Weather()
   {
      this.id = 0;
      this.cityName = "";
      this.tempMin = 0;
      this.tempMax = 0;
      this.precipitation = 0;
   }

   /**
    * Constructor de la clase.
    */
   public Weather(String cityName, int tempMin, int tempMax, int precipitation)
   {
      this.id = 0;
      this.cityName = cityName;
      this.tempMin = tempMin;
      this.tempMax = tempMax;
      this.precipitation = precipitation;
   }

   // ==============================================
   // Propiedades
   // ==============================================

   @CormObjectField(fieldClass = FormFieldInteger.class, dbTableColumn = "id",
   // fieldName = "txtId",
   label = "Código", isPrimaryKey = true, isAutogenerated = true)
   public Integer getId()
   {
      return id;
   }

   @CormFieldSetter(dbTableColumn = "id")
   public void setId(Integer id)
   {
      this.id = id;
   }

   @CormObjectField(fieldClass = FormFieldText.class, dbTableColumn = "city",
   // fieldName = "txtCity",
   label = "Ciutat", sort = FieldSortType.Ascending)
   public String getCityName()
   {
      return cityName;
   }

   @CormFieldSetter(dbTableColumn = "city")
   public void setCityName(String cityName)
   {
      this.cityName = cityName;
   }

   @CormObjectField(fieldClass = FormFieldInteger.class, dbTableColumn = "temp_lo",
   // fieldName = "txtTempLo",
   label = "Temperatura mínima")
   public Integer getTempMin()
   {
      return tempMin;
   }

   @CormFieldSetter(dbTableColumn = "temp_lo")
   public void setTempMin(Integer tempMin)
   {
      this.tempMin = tempMin;
   }

   @CormObjectField(fieldClass = FormFieldInteger.class, dbTableColumn = "temp_hi",
   // fieldName = "txtTempHi",
   label = "Temperatura màxima")
   public Integer getTempMax()
   {
      return tempMax;
   }

   @CormFieldSetter(dbTableColumn = "temp_hi")
   public void setTempMax(Integer tempMax)
   {
      this.tempMax = tempMax;
   }

   @CormObjectField(fieldClass = FormFieldInteger.class, dbTableColumn = "prcp",
   // fieldName = "txtPrcp",
   label = "Precipitació mitjana")
   public Integer getPrecipitation()
   {
      return precipitation;
   }

   @CormFieldSetter(dbTableColumn = "prcp")
   public void setPrecipitation(Integer precipitation)
   {
      this.precipitation = precipitation;
   }

   @Override
   public String toString()
   {
      return "[Weather:: ID:" + this.id + ", " + "Ciutat:" + this.cityName + ", " + "TempMin:" + this.tempMin + ", "
            + "TempMax:" + this.tempMax + ", " + "Precip:" + precipitation + "]";
   }
}
