package com.cosmo.web.sample;

import java.util.Date;

import com.cosmo.data.orm.annotations.CormObjectField;
import com.cosmo.data.orm.annotations.CormFieldSetter;
import com.cosmo.data.orm.annotations.CormObject;
import com.cosmo.data.orm.annotations.CormObjectFieldStaticList;
import com.cosmo.ui.controls.FormFieldBoolean;
import com.cosmo.ui.controls.FormFieldDate;
import com.cosmo.ui.controls.FormFieldEMail;
import com.cosmo.ui.controls.FormFieldInteger;
import com.cosmo.ui.controls.FormFieldText;
import com.cosmo.ui.controls.FormFieldTextArea;

@CormObject( formName    = "frmConvenio", 
             dbTable     = "v_convenios", 
             title       = "Accidentes Convenio",
             description = "Gestión de ofertas para seguros de accidentes de convenios.." )
public class Convenio 
{
   private int id;
   private Date fencargo;
   private Date fefecto;
   private String owner;
   private boolean polizaemitida;
   private String tomnombre;
   private String tomapellido1;
   private String tomapellido2;
   private String tomnif;
   private String tomdireccion;
   private String tomcp;
   private String tomciudad;
   private String tomprovincia;
   private String tomtelff;
   private String tomtelfm;
   private String tommail;
   private String tomfax;
   private int tomtiponif;
   private int tomsexo;
   private String comentarios;
   
   
   //==============================================
   // Constructors
   //==============================================
   
   /**
    * Constructor de la clase.
    */
   public Convenio() 
   {
      this.id = 0;
      this.fencargo = null;
      this.fefecto  = null;
      this.owner = "";
      this.polizaemitida = false;
      this.tomnombre = "";
      this.tomapellido1 = "";
      this.tomapellido2 = "";
      this.tomnif = "";
      this.tomdireccion = "";
      this.tomcp = "";
      this.tomciudad = "";
      this.tomprovincia = "";
      this.tomtelff = "";
      this.tomtelfm = "";
      this.tommail = "";
      this.tomfax = "";
      this.tomtiponif = 0;
      this.tomsexo = 0;
      this.comentarios = "";
   }

   
   //==============================================
   // Constructors
   //==============================================
   
   @CormObjectField( fieldClass           = FormFieldInteger.class, 
                     dbTableColumn        = "id", 
                     label                = "Código",
                     showInObjectListGrid = true,
                     isPrimaryKey         = true,
                     isAutogenerated      = true)
   public int getId() 
   {
      return id;
   }

   @CormFieldSetter( dbTableColumn = "id" )
   public void setId(int id) 
   {
      this.id = id;
   }

   @CormObjectField( fieldClass           = FormFieldDate.class, 
                     dbTableColumn        = "fencargo", 
                     label                = "Fecha encargo",
                     showInObjectListGrid = true)
   public Date getFencargo() 
   {
      return fencargo;
   }

   @CormFieldSetter( dbTableColumn = "fencargo" )
   public void setFencargo(Date fencargo)
   {
      this.fencargo = fencargo;
   }

   @CormObjectField( fieldClass           = FormFieldDate.class, 
                     dbTableColumn        = "fefecto", 
                     label                = "Fecha de efecto",
                     showInObjectListGrid = false)
   public Date getFefecto()
   {
      return fefecto;
   }

   @CormFieldSetter( dbTableColumn = "fefecto" )
   public void setFefecto(Date fefecto) 
   {
      this.fefecto = fefecto;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "owner", 
                     label                = "Creado por",
                     showInObjectListGrid = true)
   public String getOwner()
   {
      return owner;
   }

   @CormFieldSetter( dbTableColumn = "owner" )
   public void setOwner(String owner) 
   {
      this.owner = owner;
   }

   @CormObjectField( fieldClass           = FormFieldBoolean.class, 
                     dbTableColumn        = "polizaemitida", 
                     label                = "Poliza emitida",
                     showInObjectListGrid = false)
   public boolean isPolizaEmitida()
   {
      return polizaemitida;
   }

   @CormFieldSetter( dbTableColumn = "polizaemitida" )
   public void setPolizaEmitida(boolean polizaemitida)
   {
      this.polizaemitida = polizaemitida;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomnombre", 
                     label                = "Nombre",
                     showInObjectListGrid = true)
   public String getTomnombre()
   {
      return tomnombre;
   }

   @CormFieldSetter( dbTableColumn = "tomnombre" )
   public void setTomnombre(String tomnombre)
   {
      this.tomnombre = tomnombre;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomapellido1", 
                     label                = "Primer apellido",
                     showInObjectListGrid = true)
   public String getTomapellido1() 
   {
      return tomapellido1;
   }

   @CormFieldSetter( dbTableColumn = "tomapellido1" )
   public void setTomapellido1(String tomapellido1)
   {
      this.tomapellido1 = tomapellido1;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomapellido2", 
                     label                = "Segundo apellido",
                     showInObjectListGrid = true)
   public String getTomapellido2() 
   {
      return tomapellido2;
   }

   @CormFieldSetter( dbTableColumn = "tomapellido2" )
   public void setTomapellido2(String tomapellido2) 
   {
      this.tomapellido2 = tomapellido2;
   }

   @CormObjectField( fieldClass           = FormFieldInteger.class, 
                     dbTableColumn        = "tomtiponif", 
                     label                = "Tipo documento identidad",
                     showInObjectListGrid = false)
   @CormObjectFieldStaticList( values       = {"0",   "1",   "2"},
                               labels       = {"NIF", "CIF", "NIE"},
                               defaultValue = "0" )
   public int getTomtiponif() 
   {
      return tomtiponif;
   }
   
   @CormFieldSetter( dbTableColumn = "tomtiponif" )
   public void setTomtiponif(int tomtiponif)
   {
      this.tomtiponif = tomtiponif;
   }
   
   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomnif", 
                     label                = "Documento de identidad",
                     showInObjectListGrid = true)
   public String getTomnif()
   {
      return tomnif;
   }

   @CormFieldSetter( dbTableColumn = "tomnif" )
   public void setTomnif(String tomnif) 
   {
      this.tomnif = tomnif;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomdireccion", 
                     label                = "Dirección",
                     showInObjectListGrid = false)
   public String getTomdireccion()
   {
      return tomdireccion;
   }

   @CormFieldSetter( dbTableColumn = "tomdireccion" )
   public void setTomdireccion(String tomdireccion) 
   {
      this.tomdireccion = tomdireccion;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomcp", 
                     label                = "Código postal",
                     showInObjectListGrid = false)
   public String getTomcp() 
   {
      return tomcp;
   }

   @CormFieldSetter( dbTableColumn = "tomcp" )
   public void setTomcp(String tomcp)
   {
      this.tomcp = tomcp;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomciudad", 
                     label                = "Ciudad",
                     showInObjectListGrid = false)
   public String getTomciudad() 
   {
      return tomciudad;
   }

   @CormFieldSetter( dbTableColumn = "tomciudad" )
   public void setTomciudad(String tomciudad) 
   {
      this.tomciudad = tomciudad;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomprovincia", 
                     label                = "Provincia",
                     showInObjectListGrid = false)
   public String getTomprovincia()
   {
      return tomprovincia;
   }

   @CormFieldSetter( dbTableColumn = "tomprovincia" )
   public void setTomprovincia(String tomprovincia) 
   {
      this.tomprovincia = tomprovincia;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomtelff", 
                     label                = "Teléfono fijo",
                     showInObjectListGrid = false)
   public String getTomtelff()
   {
      return tomtelff;
   }

   @CormFieldSetter( dbTableColumn = "tomtelff" )
   public void setTomtelff(String tomtelff)
   {
      this.tomtelff = tomtelff;
   }

   @CormObjectField( fieldClass           = FormFieldText.class, 
                     dbTableColumn        = "tomtelfm", 
                     label                = "Teléfono móvil",
                     showInObjectListGrid = false)
   public String getTomtelfm()
   {
      return tomtelfm;
   }

   @CormFieldSetter( dbTableColumn = "tomtelfm" )
   public void setTomtelfm(String tomtelfm) 
   {
      this.tomtelfm = tomtelfm;
   }

   @CormObjectField( fieldClass           = FormFieldEMail.class, 
                     dbTableColumn        = "tommail", 
                     label                = "Correo electrónico",
                     showInObjectListGrid = false)
   public String getTommail() 
   {
      return tommail;
   }

   @CormFieldSetter( dbTableColumn = "tommail" )
   public void setTommail(String tommail)
   {
      this.tommail = tommail;
   }

   @CormObjectField( fieldClass           = FormFieldEMail.class, 
                     dbTableColumn        = "tomfax", 
                     label                = "FAX",
                     showInObjectListGrid = false)
   public String getTomfax() 
   {
      return tomfax;
   }

   @CormFieldSetter( dbTableColumn = "tomfax" )
   public void setTomfax(String tomfax) 
   {
      this.tomfax = tomfax;
   }

   @CormObjectField( fieldClass           = FormFieldInteger.class, 
                     dbTableColumn        = "tomsexo", 
                     label                = "Sexo",
                     showInObjectListGrid = false)
   @CormObjectFieldStaticList( values = {"0",         "1",        "2"},
                               labels = {"Masculino", "Femenino", "Empresa"} )
   public int getTomsexo()
   {
      return tomsexo;
   }

   @CormFieldSetter( dbTableColumn = "tomsexo" )
   public void setTomsexo(int tomsexo)
   {
      this.tomsexo = tomsexo;
   }
   
   @CormObjectField( fieldClass           = FormFieldTextArea.class, 
                     dbTableColumn        = "comentarios", 
                     label                = "Comentarios",
                     showInObjectListGrid = false)
   public String getComentarios()
   {
      return comentarios;
   }
   
   @CormFieldSetter( dbTableColumn = "comentarios" )
   public void setTomsexo(String comentarios)
   {
      this.comentarios = comentarios;
   }
}
